version: '3.8'

networks:
  default:

volumes:
  forum_db:

services:

  nginx:
    container_name: forum_nginx
    image: nginx:1.25.3-perl
    ports:
      - "8888:80"
    volumes:
      - ../src:/var/www/html:delegated
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel

  laravel:
    container_name: forum_dev
    build:
      context: .
    volumes:
      - ../src:/var/www/html:delegated
    depends_on:
      - postgres

  postgres:
    container_name: forum_db
    image: postgres:latest
    ports:
      - "8889:5432"
    volumes:
      - forum_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_ROOT_PASSWORD: root
